### ISSUE TITLE
Créer et effacer des fichiers et répertoires - step 1

### ISSUE THREAD

**Issue by AdrienGougeon** [mquinson/shell-exercises#1]
L'arborescence attendue n'est pas celle affichée par l'image dans le texte, la correction s'attend à trouver dir3 au niveau 0 alors que l'image le met au niveau 1.

**Comment by mquinson** [comment]
Ah voilà ! Merci beaucoup. Un ami m'avait dit qu'il arrivait pas à passer l'exo mais je voyais pas pourquoi. Ton feedback est très précieux ;)

Juste un truc: ça m'aide si tu me donnes l'URL plutot que le titre. Pour celui-là, l'identifiant d'exercice est ``usage/navigation``. Ca correspond à l'arborescence des fichiers sur disque.
