### ISSUE TITLE
navigation/quizz: sélectionner des réponses fausses n'est pas détecté

### ISSUE THREAD

**Issue by AdrienGougeon** [mquinson/shell-exercises#2]
L'étape est passée si on coche les bonnes réponses et d'autres en plus

**Comment by mquinson** [comment]
Je ne peux rien faire pour corriger ce probleme, que j'ai indiqué à upstream ici: https://github.com/katacoda/scenario-examples/issues/7

Attendons de voir leur réaction.

**Comment by mpoquet** [comment]
J'ai le même souci pour les questionnaires de type "sélectionner **des réponses** parmi N".  
Le souci n'apparaît **pas** pour les questionnaires de type "sélectionner **une réponse** parmi N".

**Comment by mquinson** [comment]
Dans le bug upstream, le mainteneur dit que ce sera résolu dans la semaine. J'espère qu'il va pas bidouiller au moment où on passe en prod...

**Comment by mquinson** [comment]
Ce bug est corrigé dans la nouvelle version, qui est une réimplémentation from scratch en local sur l'ordi de l'utilisateur.
