### ISSUE TITLE
Commentaires

### ISSUE THREAD

**Issue by AdrienGougeon** [mquinson/shell-exercises#5]
Quand on est dans le 2eme scenario le titre est "Premiers pas avec le shell", alors qu'il devrait être "Créer et effacer des fichiers et répertoires"

Dans "Créer et effacer des fichiers et répertoires" step 2, la phrase "long cd ls" n'a pas de sens.

**Comment by mquinson** [comment]
Quelle URL ? Quel exercice ? je suis perdu...
